In [1]:
import pandas as pd
import time

In [2]:
df = pd.read_csv("titanic.csv")

In [3]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [4]:
df_filter = df[["Passengerid", "Age", "Fare"]]

<h1>Base de dados</h1> 
    <p>Base de dados obtida em <a href = 'https://www.kaggle.com/heptapod/titanic'> Kaggle Titanic</a></p>
    <p>Irei basear meu codigo somente na coluna age</p>

In [5]:
print("Base de dados Antes")
display(df_filter)

Base de dados Antes

      Passengerid   Age      Fare
0               1  22.0    7.2500
1               2  38.0   71.2833
2               3  26.0    7.9250
3               4  35.0   53.1000
4               5  35.0    8.0500
...           ...   ...       ...
1304         1305  28.0    8.0500
1305         1306  39.0  108.9000
1306         1307  38.5    7.2500
1307         1308  28.0    8.0500
1308         1309  28.0   22.3583

[1309 rows x 3 columns]

<h1>Merge Sort</h1>
<p>MO Merge Sort (ordenaÃ§Ã£o por intercalaÃ§Ã£o/fusÃ£o) Ã© um algoritmo de ordenaÃ§Ã£o recursivo cujo mÃ©rito pela criaÃ§Ã£o Ã© atribuÃ­do ao fÃ­sico e matemÃ¡tico John von Neumann.</p>
<p>
    A ideia do Merge Sort Ã© dividir o vetor em dois subvetores, cada um com metade dos elementos do vetor original. Esse procedimento Ã© entÃ£o reaplicado aos dois subvetores recursivamente.
    Quando os subvetores tÃªm apenas um elemento (caso base), a recursÃ£o para. EntÃ£o, os subvetores ordenados sÃ£o fundidos (ou intercalados) num Ãºnico vetor ordenado.
</p>

In [6]:
def merge_sort(dados_para_merge):
    dados = dados_para_merge.sort_values(by="Age", kind="mergesort")
    return dados

<h1>A equaÃ§Ã£o de recorrÃªncia do Merge Sort Ã©</h1>

<h2>T(n)=2T(n/2)+Î˜(n)</h2>
<p>
    O termo 2T(n/2) Ã© o tempo para ordenar dois vetores de tamanho n/2, jÃ¡ o termo Î˜(n) Ã© o tempo para fundir/intercalar esses vetores, isto Ã©, Ã© o tempo do mÃ©todo merge. 
    A equaÃ§Ã£o de recorrÃªncia anterior jÃ¡ foi resolvida algumas vezes em postagens anteriores do blog, porÃ©m resolveremos de novo.
    Podemos utilizar o mÃ©todo de Akra-Bazzi ou o mÃ©todo mestre na resoluÃ§Ã£o. Optaremos pelo segundo.
    De acordo com o teorema mestre, temos
    a=2,b=2,f(n)=Î˜(n)
    AlÃ©m disso,
    logba=log22=1
    Como f(n)=Î˜(nlogba)=Î˜(n), entÃ£o a equaÃ§Ã£o de recorrÃªncia satisfaz o segundo caso do teorema mestre, portanto
    T(n)=Î˜(nlogbalogn)=Î˜(nlogn)
    Ou, equivalentemente, T(n)=O(nlogn). Essa complexidade Ã© a mesma no melhor caso, no caso mÃ©dio e no pior caso.
</p>


<h1>Quicksort </h1>

<p>
    Criado por Tony Hoare, o Quicksort (ordenaÃ§Ã£o rÃ¡pida) Ã© um algoritmo de ordenaÃ§Ã£o recursivo de divisÃ£o e conquista.
    Uma das suas vantagens Ã© que a ordenaÃ§Ã£o Ã© realizada no prÃ³prio vetor (in-place). Isso significa que nÃ£o hÃ¡ necessidade de alocar memÃ³ria auxiliar para realizar a ordenaÃ§Ã£o.
    Sua complexidade no tempo Ã© O(nlogn) no melhor caso e no caso mÃ©dio e O(n2) no pior caso. Contudo, em geral, o Quicksort apresenta um desempenho superior a outros algoritmos similares, como o Merge Sort.
</p>

<p>
    O Quicksort utiliza a seguinte lÃ³gica recursiva para ordenar um vetor
    Se o vetor sÃ³ possui um elemento (caso base):
    O vetor jÃ¡ estÃ¡ ordenado, retorne-o
    SenÃ£o
    Escolha um elemento do vetor, que chamaremos de pivÃ´;
    Divida o vetor em duas partiÃ§Ãµes:
    Uma partiÃ§Ã£o (Ã  esquerda) com os elementos menores ou iguais ao pivÃ´;
    Uma partiÃ§Ã£o (Ã  direita) com os elementos maiores que o pivÃ´;
    Reaplique o mÃ©todo nas duas partiÃ§Ãµes.
    Como nÃ£o existe uma regra para a escolha do pivÃ´, entÃ£o existem vÃ¡rias verÃµes do Quicksort. A versÃ£o original, de Hoare, escolhe o primeiro elemento do vetor como pivÃ´. Em Algoritmos: teoria e prÃ¡tica, Cormen [1] apresenta uma versÃ£o que utiliza o Ãºltimo elemento como pivÃ´.
    A versÃ£o de Hoare, em pseudocÃ³digo, Ã© dada a seguir
</p>

In [12]:
def quick_sort(dados_para_quick):
    dados = dados_para_quick.sort_values(by="Age", kind="quicksort")
    return dados

<h1>Complexidade assintÃ³tica</h1>
<p>O melhor caso do Quicksort ocorre quando as partiÃ§Ãµes sÃ£o balanceadas, isto Ã©, cada partiÃ§Ã£o com n/2 elementos. A equaÃ§Ã£o de recorrÃªncia nesse caso Ã© igual a do Merge Sort</p>

<h2>T(n)=2T(n/2)+Î˜(n)(melhor caso)</h2>
<p>
    Î˜(n) Ã© a complexidade no tempo do mÃ©todo de partiÃ§Ã£o. A soluÃ§Ã£o dessa recorrÃªncia Ã© T(n)=Î˜(nlogn) ou, equivalentemente, T(n)=O(logn) e pode ser obtida atravÃ©s do teorema mestre ou pelo mÃ©todo de Akra-Bazzi.
    JÃ¡ o pior caso do Quicksort ocorre quando as chamadas recursivas produzem partiÃ§Ãµes com 0 e nâˆ’1 elementos. A partiÃ§Ã£o de tamanho zero fica Ã  direita ou Ã  esquerda do pivÃ´ (depende do vetor).
    Nas versÃµes de Hoare e Cormen, esse caso patolÃ³gico ocorre quando o array estÃ¡ ordenado em ordem crescente ou descrente. A equaÃ§Ã£o de recorrÃªncia desse caso Ã©
    T(n)=T(nâˆ’1)+Î˜(n)(pior caso)
    A soluÃ§Ã£o dessa recorrÃªncia Ã© T(n)=O(n2), que Ã© a mesma complexidade (no pior caso) do Bubble Sort, Insertion Sort e Selection Sort. Esse Ã© o ponto fraco do Quicksort. Embora existam vÃ¡rias versÃµes do algoritmo que tentam minimizar esse pior caso, sempre haverÃ¡ alguma configuraÃ§Ã£o na qual o Quicksort serÃ¡ O(n2).
    A complexidade no caso mÃ©dio do Quicksort Ã© O(nlogn) e Ã© um dos pontos fortes do algoritmo. O caso mÃ©dio Ã© uma medida estatÃ­stica. Isso significa que, ao executar o Quicksort, espera-se que o tempo de execuÃ§Ã£o seja O(nlogn).
</p>

In [14]:
inicio_merge = time.time()
merge_sort(df_filter)
fim_merge = time.time()
total_time_merge =  fim_merge - inicio_merge
merge = merge_sort(df_filter)
print(" #### DEPOIS DO MERGE SORT ####")
display(merge[:50])
print(f"O fim_mergem de excuÃ§Ã£o do MERGE SORT foi {total_time_merge}")

 #### DEPOIS DO MERGE SORT ####

      Passengerid   Age      Fare
1245         1246  0.17   20.5750
1092         1093  0.33   14.4000
803           804  0.42    8.5167
755           756  0.67   14.5000
469           470  0.75   19.2583
644           645  0.75   19.2583
1172         1173  0.75   13.7750
78             79  0.83   29.0000
831           832  0.83   18.7500
1198         1199  0.83    9.3500
305           306  0.92  151.5500
1141         1142  0.92   27.7500
164           165  1.00   39.6875
172           173  1.00   11.1333
183           184  1.00   39.0000
381           382  1.00   15.7417
386           387  1.00   46.9000
788           789  1.00   20.5750
827           828  1.00   37.0042
1008         1009  1.00   16.7000
1154         1155  1.00   12.1833
1187         1188  1.00   41.5792
7               8  2.00   21.0750
16             17  2.00   29.1250
119           120  2.00   31.2750
205           206  2.00   10.4625
297           298  2.00  151.5500
340           341  2.00   26.0000
479           480  2.00   12.2875
530           531  2.00   26.0000
642           643  2.00   27.9000
824           825  2.00   39.6875
980           981  2.00   23.0000
1175         1176  2.00   20.2125
43             44  3.00   41.5792
193           194  3.00   26.0000
261           262  3.00   31.3875
348           349  3.00   15.9000
374           375  3.00   21.0750
407           408  3.00   18.7500
1300         1301  3.00   13.7750
10             11  4.00   16.7000
63             64  4.00   27.9000
171           172  4.00   29.1250
184           185  4.00   22.0250
445           446  4.00   81.8583
618           619  4.00   39.0000
691           692  4.00   13.4167
750           751  4.00   23.0000
850           851  4.00   31.2750

O fim_mergem de excuÃ§Ã£o do MERGE SORT foi 0.003002643585205078

In [15]:
inicio_quick = time.time()
quick_sort(df_filter)
fim_quick = time.time()
total_time_quick =  fim_quick - inicio_quick
quick = quick_sort(df_filter)
print(" #### DEPOIS DO QUICK SORT ####")
display(quick[:50])
print(f"O tem de excuÃ§Ã£o do QUICK SORT foi {total_time_quick}")

 #### DEPOIS DO QUICK SORT ####

      Passengerid   Age      Fare
1245         1246  0.17   20.5750
1092         1093  0.33   14.4000
803           804  0.42    8.5167
755           756  0.67   14.5000
644           645  0.75   19.2583
469           470  0.75   19.2583
1172         1173  0.75   13.7750
831           832  0.83   18.7500
78             79  0.83   29.0000
1198         1199  0.83    9.3500
305           306  0.92  151.5500
1141         1142  0.92   27.7500
164           165  1.00   39.6875
1008         1009  1.00   16.7000
381           382  1.00   15.7417
172           173  1.00   11.1333
1187         1188  1.00   41.5792
1154         1155  1.00   12.1833
183           184  1.00   39.0000
788           789  1.00   20.5750
827           828  1.00   37.0042
386           387  1.00   46.9000
479           480  2.00   12.2875
530           531  2.00   26.0000
642           643  2.00   27.9000
297           298  2.00  151.5500
1175         1176  2.00   20.2125
824           825  2.00   39.6875
980           981  2.00   23.0000
340           341  2.00   26.0000
205           206  2.00   10.4625
7               8  2.00   21.0750
16             17  2.00   29.1250
119           120  2.00   31.2750
261           262  3.00   31.3875
407           408  3.00   18.7500
348           349  3.00   15.9000
374           375  3.00   21.0750
1300         1301  3.00   13.7750
193           194  3.00   26.0000
43             44  3.00   41.5792
10             11  4.00   16.7000
184           185  4.00   22.0250
869           870  4.00   11.1333
171           172  4.00   29.1250
445           446  4.00   81.8583
850           851  4.00   31.2750
618           619  4.00   39.0000
691           692  4.00   13.4167
750           751  4.00   23.0000

O tem de excuÃ§Ã£o do QUICK SORT foi 0.002005338668823242

In [ ]:
from IPython.display import display_html
def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

In [10]:
#display_side_by_side(merge,quick)