In [1]:
import pandas as pd

In [2]:
d1 = pd.read_csv('data_orders_test.csv')

In [3]:
d1

,category,price,freight_value,customer_lat,customer_lng,seller_lat,seller_lng,order_status,order_approved_at,order_delivered_customer_date
0,informatica_acessorios,79.90,15.31,-29.166314,-51.178314,-23.413743,-51.907543,delivered,2017-09-26 17:26:24,2017-10-06 13:42:33
1,cama_mesa_banho,39.99,18.23,-16.697612,-49.275774,-21.757321,-48.829744,delivered,2018-03-15 12:49:18,2018-03-28 20:44:41
2,esporte_lazer,27.90,14.52,-23.571450,-46.647981,-23.390607,-51.446644,delivered,2017-03-07 11:55:15,2017-03-20 12:04:28
3,telefonia,779.00,27.38,-19.925110,-44.259942,-23.770304,-53.293996,delivered,2018-08-16 10:10:26,2018-08-24 15:36:38
4,esporte_lazer,43.00,18.40,-31.757103,-52.317667,-24.008923,-46.419125,delivered,2018-06-23 13:40:01,2018-07-06 23:44:36
...,...,...,...,...,...,...,...,...,...,...
1995,beleza_saude,287.70,24.94,-12.253483,-38.951224,-23.571153,-46.620436,delivered,2018-05-02 20:38:42,2018-05-15 10:49:55
1996,automotivo,38.00,25.63,-29.738280,-51.142599,-21.422173,-45.964344,delivered,2018-01-09 07:17:40,2018-01-22 21:08:58
1997,pet_shop,99.20,21.11,-22.325549,-49.094331,-22.729029,-47.641148,delivered,2018-04-13 17:55:13,2018-04-18 16:22:00
1998,cama_mesa_banho,15.90,11.85,-22.692949,-46.982878,-21.757321,-48.829744,delivered,2017-06-10 03:03:37,2017-06-22 14:08:44
1999,esporte_lazer,54.90,15.26,-30.090468,-51.235530,-25.528424,-49.275490,delivered,2018-05-08 04:33:58,2018-05-19 16:07:23